### ISSUE TITLE
hard coded references

### ISSUE THREAD

**Issue by wowasa** [cpetrakis/RDFVisualizer-webapp#2]
Dear Kostas, 

I just downloaded, compiled and deployed the project on tomcat 8.5 but it doesn't run "out of the box". At a brief look into the source code I see a couple of hardcoded references to configuration files. Is there a certain reason that these files are not simply put on the classpath to be loaded by the ClassLoader? 

best regards
wowasa

**Comment by cpetrakis** [comment]
Hi wowasa,

In order to use the tool, you should fill in the property values in config.properties with the right way as explained in README file.

Hard coded references are three properties (filename, default_folder, priorities_xml).

- You have to fill the first two (filename & default_folder) only if you want to visualize data from a specific .ttl file in your system. These paths are not on classpath because the folder can be anywhere (user's decision) in the filesystem.

- priorities_xml property must be filled in all cases. This path could be on classpath as you wisely mentioned, but it is hard coded (as a request) in case of a user would prefer to have this file anywhere in the filesystem, or have more than one properties.xml and visualize the same data with different properties order, by changing only a path in config.properties and not replacing the file in webapp folder every time.
Thanks for your feedback.

Best,
Kostas

**Comment by wowasa** [comment]
Dear Kostas, 

thank you! At the end it turned out to be a problem with maven. After deleting and reloading the repository I could compile a version which works on tomcat 8.5. 
So I'm closing this issue now. 

best regards
wowasa
